version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '8642'
      POSTGRES_DB: 'database_name'
    ports:
      - '5454:5432'
    volumes:
      - /home/containers/Docker-Compose/db:/var/lib/postgresql/data
